# Generated by Django 4.2.16 on 2024-10-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_satay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.player')),
                ('satay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.satay')),
            ],
        ),
    ]
