# Generated by Django 4.2.16 on 2024-10-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='malsheid',
        ),
        migrations.AddField(
            model_name='rating',
            name='smaak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
