# Generated by Django 5.0.8 on 2024-10-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_rename_score_rating_malsheid_rating_smaak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='malsheid',
            new_name='taste',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='smaak',
            new_name='tenderness',
        ),
    ]
