# Generated by Django 5.0.8 on 2024-10-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_playercompetition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satay',
            name='id',
        ),
        migrations.AlterField(
            model_name='satay',
            name='cook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='competition.playercompetition'),
        ),
    ]
